### ISSUE TITLE
Multi-organ segmentation over multiple datasets

### ISSUE THREAD

**Issue by ChandraV76** [DIAL-RPI/PIPO-FAN#2]
Dear @seconds7 ,

Thank you for sharing your work.

I have question about how to train the network with multiple dataset. (It's not written yet on that section)
Currently I have KiTS, LITS, and Decathlon (Pancreas and Spleen) dataset, I would like to train them all together.
Waiting for your guide.

Best regards,
ChandraV76

**Comment by xifang001** [comment]
Hi, @ChandraV76,

Thanks for your question. The training method is same as training the network on one dataset. To train multiple datasets together, you need to change the folder_training and folder_validation to fit your own dataset. Then, you need to specify the class number for multi organ segmentation (eg. liver 1, kidney 2) and modify the training policy part in Row 614 according to these labels in train and validation part. 
You can refer to the paper for more details. I will complete the multiple dataset part in near future.

Thanks,
Xi

**Comment by ChandraV76** [comment]
Thank you. Now I got another error

`Traceback (most recent call last):
  File "train_sf_partial.py", line 581, in <module>
    train_loader4 = dl2.DataLoader(dataset_train4, batch_size=args.batchsize, shuffle=True, num_workers=4, drop_last=False)
  File "/home/chandrav76/anaconda3/envs/pipo-fan/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/chandrav76/anaconda3/envs/pipo-fan/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
`
I put all my training data into
`/home/chandrav76/Documents/PIPO-FAN/pipo_fan/dataset/BTCV/training`
with all the data inside named `image0.nii.gz` to `image9.nii.gz` respectively. Same for the label with `label` prefix.
I also already set those 4 folders like this
`
checkpoing_dir = path.expanduser('/home/chandrav76/Documents/PIPO-FAN/pipo_fan/checkpoint/')
log_dir = path.expanduser('/home/chandrav76/Documents/PIPO-FAN/pipo_fan/log/')
folder_validation_4 = '/home/chandrav76/Documents/PIPO-FAN/pipo_fan/dataset/BTCV/validation/'
`

in the `dataset_muor_2D.py` i modifed this part to matching my filenames
`res = glob.glob(path.join(root_dir, 'image*.nii'))`
`seg_name = img_name.replace('image', 'label')`

FYI, I'm using BTCV dataset and want to train it with all the 13 labels inside. Am I missing something?

**Comment by ChandraV76** [comment]
Thank you.
I plan to segment out all the 13 organs in BTCV dataset. which parameter should I set? can you guide me?

**Comment by xifang001** [comment]
Hi, @ChandraV76 ,
 I would be happy to guide you. You can try training the model on BTCV only to segment all 13 organs. To do that, you can first comment row 614-614 in the train_sf_partial.py. Then class number in row 453 should be fixed to 14. Some default path should be modified according to your own data path. Run this file, then it should work. If you encounter any problem or have any suggestions, don't hesitate to let me know.

**Comment by ChandraV76** [comment]
Thank you. 

> comment row 614-614

Maybe you mean 614-624.

I also changed the dataset_muor_2D.py to match the files structures.
I also have LITS, KiTS, and Spleen (Medical Decathlon) dataset. Is it the same parameters for train them together for 13 organs segmentation (also uncomment the 614-624 rows)?

**Comment by xifang001** [comment]
Yes, 614-624. Have you succeed in running the file for multi-organ segmentation already? After then, to train all datasets together, you need to iteratively train these datasets epoch by epoch. Same parameters are used to train them.

**Comment by ChandraV76** [comment]
Yes, its working. I also changed it using CPU ( by changing `cuda()` to `cpu()` ). But I stopped my training in the epoch 32th because of my limited hardware to avoid over-heating on my laptop (I afraid of the fan noise). Later I will run training on my lab computer after the office started when this pandemic over.
In this case I have no intent to segmented out the tumor, just taking out the organs. Should I manually remove the tumor label first from LiTS and KiTS?

**Comment by xifang001** [comment]
In my experiment, the tumor is regarded as part of the organ. For example, when training on LiTS data, the class number of tumor is changed from 2 into 1, which is the same as liver.

**Comment by sharonlee12** [comment]
> In my experiment, the tumor is regarded as part of the organ. For example, when training on LiTS data, the class number of tumor is changed from 2 into 1, which is the same as liver.
hello,sorry to bother you,I try to modify in the training file like this:
if(data_type=='1'):
label_batch[label_batch == 1] = 1 # liver
label_batch[label_batch == 2] = 1 # liver
if(data_type=='2'):
label_batch[label_batch == 1] = 2 #kid
label_batch[label_batch == 2] = 2 #kid
if(data_type=='3'):
label_batch[label_batch == 1] = 3 #spleen
if(data_type=='4'):
label_batch[label_batch == 1] = 3 # spleen
label_batch[label_batch == 2] = 2 # rkid + lkid
label_batch[label_batch == 3] = 2 # rkid + lkid
label_batch[label_batch == 4] = 0 #
label_batch[label_batch == 5] = 0 #
label_batch[label_batch == 6] = 1 # liver
label_batch[label_batch > 6] = 0
like this:
![image](https://github.com/DIAL-RPI/PIPO-FAN/assets/120789038/4d8eadeb-1303-4965-86f9-450bea8a16f8)


but while training there is an error:
../aten/src/ATen/native/cuda/NLLLoss2d.cu:93: nll_loss2d_forward_kernel: block: [2,0,0], thread: [384,0,0] Assertion t >= 0 && t < n_classes failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:93: nll_loss2d_forward_kernel: block: [2,0,0], thread: [385,0,0] Assertion t >= 0 && t < n_classes failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:93: nll_loss2d_forward_kernel: block: [2,0,0], thread: [386,0,0] Assertion t >= 0 && t < n_classes failed.

I hope to know where is the problem with my settings

**Comment by sharonlee12** [comment]
> In my experiment, the tumor is regarded as part of the organ. For example, when training on LiTS data, the class number of tumor is changed from 2 into 1, which is the same as liver.

hello,I try to modify in the training file like this:
if(data_type=='1'):
label_batch[label_batch == 1] = 1 # liver
label_batch[label_batch == 2] = 1 # liver
if(data_type=='2'):
label_batch[label_batch == 1] = 2 #kid
label_batch[label_batch == 2] = 2 #kid
if(data_type=='3'):
label_batch[label_batch == 1] = 3 #spleen
if(data_type=='4'):
label_batch[label_batch == 1] = 3 # spleen
label_batch[label_batch == 2] = 2 # rkid + lkid
label_batch[label_batch == 3] = 2 # rkid + lkid
label_batch[label_batch == 4] = 0 #
label_batch[label_batch == 5] = 0 #
label_batch[label_batch == 6] = 1 # liver
label_batch[label_batch > 6] = 0
![image](https://github.com/DIAL-RPI/PIPO-FAN/assets/120789038/ae767d04-1bb1-4b32-9fec-0e39ff3cb72e)
but while training there is an error:
../aten/src/ATen/native/cuda/NLLLoss2d.cu:93: nll_loss2d_forward_kernel: block: [2,0,0], thread: [384,0,0] Assertion t >= 0 && t < n_classes failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:93: nll_loss2d_forward_kernel: block: [2,0,0], thread: [385,0,0] Assertion t >= 0 && t < n_classes failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:93: nll_loss2d_forward_kernel: block: [2,0,0], thread: [386,0,0] Assertion t >= 0 && t < n_classes failed.

I hope to know where is the problem with my settings
