### ISSUE TITLE
segment_sf.py file missing

### ISSUE THREAD

**Issue by Cyboteen** [DIAL-RPI/PIPO-FAN#6]
Hi, Xi. 
Thank you for sharing your code! 
I have only one multi-organ dataset on which I want to evaluate PIPO-FAN. And I have a few questions regarding it:

1. You said that if training on a single dataset using PIPO-FAN, one should use `train_sf_partial.py`. But it seems to have multiple datasets loaded. Could you tell me how to train it with one single dataset?
2. I have trained one model using `train_concave0.py`. Could you show me how to infer and calculate metrics (e.g. dice)? It seems that the file `segment_sf.py` you mentioned in README is missing. 

Thank you for your time!

**Comment by xifang001** [comment]
Sorry for the late reply. If you want to run the algorithm on one dataset, the dataset part should be modified.  line 614-626 should be removed and line 628 should be uncommented. The segment_sf and segment_sf_partial are the same. The dice_coefficient function is on line 105. For more details and quick reply, you can directly send me e-mail at xifang96@gmail.com.

Best,
Xi
