### ISSUE TITLE
Spleen dataset 

### ISSUE THREAD

**Issue by Huiimin5** [DIAL-RPI/PIPO-FAN#7]
Hi, thank you a lot for your contribution in this work.
How do you have the access to the spleen dataset in your work? I cannot find the link for download in paper [16]. 
Or is it confidential and you can use the data because cooperation with that research team?
In that case, maybe I can use spleen dataset from MSD.

**Comment by xifang001** [comment]
Thanks for asking. For your question, yes, you can use the spleen dataset from MSD. Indeed the spleen dataset you mentioned is the one we use in our paper, you can check the information in the paper which describes the MSD dataset at https://arxiv.org/pdf/1902.09063.pdf.

Best,
Xi

**Comment by Huiimin5** [comment]
Now it's clear to me.Thank you so much for your reply.
