### ISSUE TITLE
deep pyramid supervision

### ISSUE THREAD

**Issue by AustinYuAo** [DIAL-RPI/PIPO-FAN#9]
Hi!
I found that deep pyramid supervision is used in training PIPO( train_concave0.py)?
However, deep pyramid supervision is not  used in training PIPO-FAN( train_sf_partial.py).
Is that right?

**Comment by xifang001** [comment]
Thanks for asking. I finetuned PIPO-FAN by using the pretrained PIPO. So deep pyramid supervision is included.

**Comment by AustinYuAo** [comment]
Thank you very much for your answer！
